version: '3.8'

services:
  express_app:
    build: .
    container_name: express_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - app_network 

  nginx:
    image: nginx
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - express_app
    networks:
      - app_network 

networks:
  app_network:  
    driver: bridge
