name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: SSH into EC2 and stop the server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
        pm2 stop all || echo "No PM2 process found"
        EOF

    - name: Pull the latest changes from the repository
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
        cd /home/ubuntu/lenden
        git reset --hard origin/main
        git pull origin main
        EOF

    - name: Install dependencies and restart server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
        cd /home/ubuntu/lenden/server
        npm install
        pm2 restart all || pm2 start npm --name "lenden-server" -- start
        EOF
