name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up EC2 private key for SSH access
      run: echo "${{ secrets.EC2_KEY }}" > private_key.pem
      # shell: bash

    - name: SSH into EC2 and stop the server
      run: |
        chmod 600 private_key.pem
        ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "pkill -f 'npm start' || true"
          
    - name: Pull the latest changes from the repository
      run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "cd home/ubuntu/lenden && git pull origin main"

    - name: Deploy the server
      run: |
        ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "cd home/ubuntu/lenden/server && npm install && nohup npm start &"
        EOF
