name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up EC2 private key for SSH access
      run: echo "${{ secrets.EC2_KEY }}" > private_key.pem
      shell: bash

    - name: SSH into EC2 and deploy the application
      run: |
        chmod 600 private_key.pem
        ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          # Stop the currently running npm server by killing the process
          echo "Stopping existing npm server..."
          pkill -f 'npm start' || true
          
          # Pull the latest changes from the repository
          echo "Pulling the latest code from GitHub..."
          cd home/ubuntu/lenden
          git pull origin main
          
           # CD into the server directory
          echo "CD into the server directory..."
          cd home/ubuntu/lenden/server

          # Install the dependencies
          echo "Installing dependencies..."
          npm install
          
          # Start the server again
          echo "Starting the server..."
          nohup npm start &  # Run npm start in the background
        EOF
