name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up EC2 private key for SSH access
      run: echo "${{ secrets.EC2_KEY }}" > private_key.pem
      shell: bash

    - name: Stop running npm server
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} "pkill -f 'npm start' || true"
      
    - name: Pull latest code from GitHub
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} "cd /lenden && git pull origin main"

    - name: Install dependencies and restart the server
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /lenden
          npm install
          nohup npm start &  # Run npm start in the background
        EOF